version: "3"
services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # So it can run other containers
      - ./tmp:/app/tmp                              # If using local input/output folders
